---
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.16.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v2.3.1"
    hooks:
      - id: "mypy"
        args: ["--show-traceback"]
        additional_dependencies:
          - "django-stubs"
          - "nox"
          - "pytest"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.32.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.9.0" # Replace with the latest tag on GitHub
    hooks:
      - id: djade
        args: [--target-version, "5.1"]
